# Generated by Django 5.2.1 on 2025-05-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0002_admin_is_logged_in_teacher_is_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='teacher_id',
            field=models.IntegerField(),
        ),
    ]
