# Generated by Django 5.2.1 on 2025-05-17 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0003_alter_task_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='teacher_id',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='taskManager.teacher'),
        ),
    ]
