# Generated by Django 5.2.1 on 2025-05-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0004_alter_task_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskDescription',
            field=models.TextField(),
        ),
    ]
